INCLUDEPATH += $$PWD/Rx/v2/src
DEPENDPATH += $$PWD

HEADERS += \
    $$PWD/Rx/v2/src/rxcpp/rx-connectable_observable.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-coordination.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-coroutine.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-grouped_observable.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-includes.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-lite.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-notification.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-observable.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-observer.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-operators.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-predef.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-scheduler.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-sources.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-subjects.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-subscriber.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-subscription.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-test.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-trace.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx-util.hpp \
    $$PWD/Rx/v2/src/rxcpp/rx.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-all.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-amb.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-any.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-buffer_count.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-buffer_time.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-buffer_time_count.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-combine_latest.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-concat.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-concat_map.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-connect_forever.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-debounce.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-delay.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-distinct.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-distinct_until_changed.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-element_at.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-filter.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-finally.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-flat_map.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-group_by.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-ignore_elements.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-lift.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-map.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-merge.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-multicast.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-observe_on.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-on_error_resume_next.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-pairwise.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-publish.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-reduce.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-ref_count.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-repeat.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-replay.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-retry.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-sample_time.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-scan.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-sequence_equal.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-skip.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-skip_last.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-skip_until.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-start_with.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-subscribe.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-subscribe_on.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-switch_if_empty.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-switch_on_next.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-take.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-take_last.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-take_until.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-take_while.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-tap.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-time_interval.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-timeout.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-timestamp.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-window.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-window_time.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-window_time_count.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-window_toggle.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-with_latest_from.hpp \
    $$PWD/Rx/v2/src/rxcpp/operators/rx-zip.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-currentthread.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-eventloop.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-immediate.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-newthread.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-runloop.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-sameworker.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-test.hpp \
    $$PWD/Rx/v2/src/rxcpp/schedulers/rx-virtualtime.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-create.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-defer.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-empty.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-error.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-interval.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-iterate.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-never.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-range.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-scope.hpp \
    $$PWD/Rx/v2/src/rxcpp/sources/rx-timer.hpp \
    $$PWD/Rx/v2/src/rxcpp/subjects/rx-behavior.hpp \
    $$PWD/Rx/v2/src/rxcpp/subjects/rx-replaysubject.hpp \
    $$PWD/Rx/v2/src/rxcpp/subjects/rx-subject.hpp \
    $$PWD/Rx/v2/src/rxcpp/subjects/rx-synchronize.hpp
